
class RetryException(Exception):
    pass

class InitException(Exception):
    pass